name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      
    - run: msbuild ${{ github.event.repository.name }}.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x86
    - run: cp Win32\Release\${{ github.event.repository.name }}.asi ${{ github.event.repository.name }}.asi

    - uses: robinraju/release-downloader@v1.11
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader.zip"

    - name: Prepare Ultimate ASI Loader
      run: |
        unzip Ultimate-ASI-Loader.zip -d .\
        C:\msys64\usr\bin\wget.exe -O .\UltimateASILoader_LICENSE.md https://raw.githubusercontent.com/ThirteenAG/Ultimate-ASI-Loader/master/license
        
    - name: Create Directory Structure
      run: |
        mkdir .\zip\ea\bin_ship
        mkdir .\zip\gog\bin_ship

    - name: Prepare GOG Files
      run: |
        cp ${{ github.event.repository.name }}.asi .\zip\gog\bin_ship\
        cp ${{ github.event.repository.name }}.ini .\zip\gog\bin_ship\
        cp dinput8.dll .\zip\gog\bin_ship\dinput8.dll
        cp UltimateASILoader_LICENSE.md .\zip\gog\
        New-Item -Path ".\zip\gog\EXTRACT_TO_GAME_FOLDER" -ItemType File
    
    - name: Create GOG Zip
      run: |
        cd .\zip\gog\
        7z a -r -tzip ..\..\${{ github.event.repository.name }}_${{ github.event.inputs.version }}.zip .\*

    - name: Prepare EA Files
      run: |
        cp ${{ github.event.repository.name }}.asi .\zip\ea\bin_ship\
        cp ${{ github.event.repository.name }}.ini .\zip\ea\bin_ship\
        cp dinput8.dll .\zip\ea\bin_ship\winhttp.dll
        cp UltimateASILoader_LICENSE.md .\zip\ea\
        New-Item -Path ".\zip\ea\EXTRACT_TO_GAME_FOLDER" -ItemType File
    
    - name: Create EA Zip
      run: |
        cd .\zip\ea\
        7z a -r -tzip ..\..\${{ github.event.repository.name }}_${{ github.event.inputs.version }}_EA.zip .\*

    - name: Update release_body.md
      run: |
        $releaseBody = "release_body.md"
        $zipName = "${{ github.event.repository.name }}_${{ github.event.inputs.version }}.zip" 
        (Get-Content $releaseBody -Raw) -replace '<RELEASE_ZIP_NAME>', $zipName | Set-Content $releaseBody
        $EAZipName = "${{ github.event.repository.name }}_${{ github.event.inputs.version }}_EA.zip" 
        (Get-Content $releaseBody -Raw) -replace '<RELEASE_ZIP_NAME_EA>', $EAZipName | Set-Content $releaseBody
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}_${{ github.event.inputs.version }}.zip, ${{ github.event.repository.name }}_${{ github.event.inputs.version }}_EA.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.version }}
        name: "${{ github.event.inputs.version }}"
        draft: true
        bodyFile: "release_body.md"
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
